version: "3.8"

services:
    database:
        image: postgres:12
        restart: always
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - ./sql:/docker-entrypoint-initdb.d

    api:
        image: mychest-api:latest
        restart: always
        depends_on:
            - database
        ports:
            - 3000:3000
        environment:
            TYPEORM_HOST: database
