version: "3.8"

services: 
    mychestDatabase:
        image: postgres:12
        restart: always
        environment: 
            POSTGRES_PASSWORD: "password"
        ports: 
            - 5432:5432
        volumes: 
            - ./sql:/docker-entrypoint-initdb.d